src/Hub/HubBundle/Entity/User.php
<?php

namespace Hub\HubBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table(name="user", uniqueConstraints={@ORM\UniqueConstraint(name="email", columns={"email"})})
 * @ORM\Entity
 */
class User implements UserInterface {

    /**
     * @var string
     *
     * @ORM\Column(name="user", type="string", length=50, nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $user;

    /**
     * @var string
     *
     * @ORM\Column(name="role", type="string", length=50, nullable=false)    
     *    
     */
    private $role;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=50, nullable=false)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="country", type="string", length=50, nullable=true)
     */
    private $country;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=50, nullable=true)
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=50, nullable=false)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="website", type="string", length=50, nullable=true)
     */
    private $website;

    /**
     * @var string
     *
     * @ORM\Column(name="language", type="string", length=50, nullable=false)
     */
    private $language;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="registrationDate", type="date", nullable=true)
     */
    private $registrationdate;

    /**
     * @var boolean
     *
     * @ORM\Column(name="active", type="boolean", nullable=false)
     */
    private $active;

    /**
     * @var string
     *
     * @ORM\Column(name="salt", type="string", length=255, nullable=false)
     */
    private $salt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="lastAccess", type="date", nullable=true)
     */
    private $lastaccess;

    /**
     * @var string
     *
     * @ORM\Column(name="perfilPhoto", type="string", length=255, nullable=false)
     */
    private $perfilphoto;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="Notification", mappedBy="useremitter")
     * 
     */
    private $idnotificationemitter;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="Notification", mappedBy="userreceiver")
     * 
     */
    private $idnotificationreceiver;

    /**
     * Constructor
     */
    public function __construct() {
        $this->idnotificationemitter = new \Doctrine\Common\Collections\ArrayCollection();
        $this->idnotificationreceiver = new \Doctrine\Common\Collections\ArrayCollection();
        $this->salt = md5(uniqid(null, true));
        $this->registrationdate = new \DateTime(null, null);
    }

    public function setRole($role) {
        $this->role = $role;
    }

    public function getRole() {
        return $this->role;
    }

    /**
     * Set user
     *
     * @param string $user
     *
     * @return User
     */
    public function setUser($user) {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return string
     */
    public function getUser() {
        return $this->user;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return User
     */
    public function setPassword($password) {
        $this->password = $password;

        return $this;
    }

    /**
     * Set country
     *
     * @param string $country
     *
     * @return User
     */
    public function setCountry($country) {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return string
     */
    public function getCountry() {
        return $this->country;
    }

    /**
     * Set city
     *
     * @param string $city
     *
     * @return User
     */
    public function setCity($city) {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity() {
        return $this->city;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return User
     */
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Set website
     *
     * @param string $website
     *
     * @return User
     */
    public function setWebsite($website) {
        $this->website = $website;

        return $this;
    }

    /**
     * Get website
     *
     * @return string
     */
    public function getWebsite() {
        return $this->website;
    }

    /**
     * Set language
     *
     * @param string $language
     *
     * @return User
     */
    public function setLanguage($language) {
        $this->language = $language;

        return $this;
    }

    /**
     * Get language
     *
     * @return string
     */
    public function getLanguage() {
        return $this->language;
    }

    /**
     * Set registrationdate
     *
     * @param \DateTime $registrationdate
     *
     * @return User
     */
    public function setRegistrationdate($registrationdate) {
        $this->registrationdate = $registrationdate;

        return $this;
    }

    /**
     * Get registrationdate
     *
     * @return \DateTime
     */
    public function getRegistrationdate() {
        return $this->registrationdate;
    }

    /**
     * Set active
     *
     * @param boolean $active
     *
     * @return User
     */
    public function setActive($active) {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean
     */
    public function getActive() {
        return $this->active;
    }

    /**
     * Set salt
     *
     * @param string $salt
     *
     * @return User
     */
    public function setSalt($salt) {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Set lastaccess
     *
     * @param \DateTime $lastaccess
     *
     * @return User
     */
    public function setLastaccess($lastaccess) {
        $this->lastaccess = $lastaccess;

        return $this;
    }

    /**
     * Get lastaccess
     *
     * @return \DateTime
     */
    public function getLastaccess() {
        return $this->lastaccess;
    }

    /**
     * Set perfilphoto
     *
     * @param string $perfilphoto
     *
     * @return User
     */
    public function setPerfilphoto($perfilphoto) {
        $this->perfilphoto = $perfilphoto;

        return $this;
    }

    /**
     * Get perfilphoto
     *
     * @return string
     */
    public function getPerfilphoto() {
        return $this->perfilphoto;
    }

    /**
     * Add idnotificationemitter
     *
     * @param \Hub\HubBundle\Entity\Notification $idnotification
     *
     * @return Notification
     */
    public function addIdnotificationemitter(\Hub\HubBundle\Entity\Notification $idnotification) {
        $this->idnotificationemitter[] = $idnotification;
        return $this;
    }

    /**
     * Remove idnotificationemitter
     *
     * @param \Hub\HubBundle\Entity\Notification $idnotification
     */
    public function removeIdnotificationemitter(\Hub\HubBundle\Entity\Notification $idnotification) {
        $this->idnotificationemitter->removeElement($idnotification);
    }

    /**
     * Get $idnotificationemitter
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getIdnotificationemitter() {
        return $this->idnotificationemitter;
    }

    /**
     * Add idnotificationreceiver
     *
     * @param \Hub\HubBundle\Entity\Notification $idnotification
     *
     * @return Notification
     */
    public function addIdnotificationreceiver(\Hub\HubBundle\Entity\Notification $idnotification) {
        $this->idnotificationreceiver[] = $idnotification;
        return $this;
    }

    /**
     * Remove idnotificationreceiver
     *
     * @param \Hub\HubBundle\Entity\Notification $idnotification
     */
    public function removeIdnotificationreceiver(\Hub\HubBundle\Entity\Notification $idnotification) {
        $this->idnotificationreceiver->removeElement($idnotification);
    }

    /**
     * Get $idnotificationreceiver
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getIdnotificationreceiver() {
        return $this->idnotificationreceiver;
    }

    /**
     * @inheritDoc
     */
    public function getSalt() {
        return $this->salt;
    }

    /**
     * @inheritDoc
     */
    public function getPassword() {
        return $this->password;
    }

    /**
     * @inheritDoc
     */
    public function getUsername() {
        return $this->user;
    }

    /**
     * @inheritDoc
     */
    public function getRoles() {
        return array($this->role);
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials() {
        
    }

    /**
     * @inheritDoc
     */
    public function equals(UserInterface $user) {
        return $this->user === $user->getUsername();
    }

}

src/Hub/HubBundle/Controller/DefaultController.php
<?php

namespace Hub\HubBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Hub\HubBundle\Entity\Category;
use Hub\HubBundle\Entity\User;
use Hub\HubBundle\Entity\Basicuser;
use Hub\HubBundle\Entity\Profession;
use Hub\HubBundle\Entity\Professional;
use Hub\HubBundle\Entity\Skill;
use Hub\HubBundle\Entity\Business;
use Hub\HubBundle\Entity\Notification;

class DefaultController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $user = 'balmarales'; //user loged
        $receiver = $em->getRepository('HubBundle:User')->find($user);    
        $count = count($receiver->getIdnotificationreceiver()); 
       return $this->render('HubBundle:Default:index.html.twig', array('notifications' => $receiver->getIdnotificationreceiver(), 'count' => $count));
       //  return $this->render('HubBundle:Default:signup.php');
    }
    public function signupAction()
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository('HubBundle:User');
        $users = $repository->findAll();      
        return $this->render('HubBundle:Default:signup.html.twig', array('users' => $users));
              
    }
    
    public function loginAction()
    {
        return $this->render('HubBundle:Default:login.html.twig');
    }     

    public function test1Action() {
        /*$em = $this->getDoctrine()->getManager();
        $request = $this->container->get('request_stack')->getCurrentRequest();
        $emitter = $em->getRepository('HubBundle:User')->find('leo');
        $receiver = $em->getRepository('HubBundle:User')->find('otro');

        /*
        $notification = new Notification();
        $notification->setUserreceiver($receiver);
        $notification->setUseremitter($emitter);
        $notification->setMessage('hola, necesito que me llames');
        $notification->setIsread(false);
        $em->persist($notification);
        $em->flush();
        */
       /* $dir = $this->container->getParameter('kernel.root_dir').'/../web/bundles/hub/perfil';

        if ($request->getMethod() == 'POST') {
        $ext = $request->files->get('photo1')->guessExtension();
        $request->files->get('photo1')->move($dir, 'testPhoto1'.'.'.$ext);
        }*/
        
        $request = $this->container->get('request_stack')->getCurrentRequest();
        $name = "myname";

        if ($request->getMethod() == 'POST') {
            $name = uniqid();
            $ext = $request->files->get('archivo')->guessExtension();
             $dir = $this->container->getParameter('kernel.root_dir').'/../web/bundles/hub/businessImages';

            $request->files->get('archivo')->move($dir, $name.'.'.$ext);
        } 
}

public function test2Action() {
       return $this->render('HubBundle:Default:test1.html.twig');
}    

public function test3Action() {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository('HubBundle:Category');
        $categories = $repository->findAll();
        $repository = $em->getRepository('HubBundle:Professional');
        $professionals = $repository->findAll();
       return $this->render('HubBundle:Default:list.html.twig', array('categories' => $categories, 'professionals' => $professionals));
}
}

src/Hub/HubBundle/Resources/views/Default/list.html.twig
{# empty Twig template #}

{% extends 'head_Template.html.twig' %}

{% block color %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        {% if app.user.roles[0] == "ROLE_BUSINESS"  %}
            <link href="{{asset('bundles/hub/css/skins/pink.css')}}" rel="stylesheet">
        {% elseif app.user.roles[0] == "ROLE_PROFESSIONAL"  %}
            <link href="{{asset('bundles/hub/css/skins/orange.css')}}" rel="stylesheet">
        {% elseif app.user.roles[0] == "ROLE_USER" %}   
            <link href="{{asset('bundles/hub/css/skins/blue.css')}}" rel="stylesheet">
        {% else %}
            <link href="{{asset('bundles/hub/css/skins/red.css')}}" rel="stylesheet">
        {% endif %}    
    {% endif %}
{% endblock %}

{% block content %}
    <!-- ================ -->
    <section class="main-container">

        <div class="container">
            <div class="row">

                <!-- main start -->
                <!-- ================ -->
                <div class="main col-md-12">

                    <!-- page-title start -->
                    <!-- ================ -->
                    <h1 class="page-title">Professionals</h1>
                    <div class="separator-2"></div>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas nulla suscipit <br class="hidden-sm hidden-xs"> unde rerum mollitia dolorum.</p>
                    <!-- page-title end -->

                    <!-- isotope filters start -->
                    <div class="filters">
                        <ul class="nav nav-pills">
                            <li class="active"><a href="#" data-filter="*">All</a></li>
                                {% for category in categories%}

                                <li><a href="#" data-filter=".{{category.getIdcategory()}}">{{category.getCategoryname()}}</a></li>
                                
                                {%endfor%}
                        </ul>
                    </div>
                    <!-- isotope filters end -->

                    <!-- portfolio items start -->
                    <div class="isotope-container row">
                        {%for professional in professionals %}
                        <div class="col-md-4 col-sm-6 isotope-item {{professional.getIdcategory().getIdcategory()}}">
                            <div class="image-box">
                                <div class="overlay-container">
                                    <img src="{{asset("bundles/hub/perfil/" ~ professional.getUser().getPerfilphoto() )}}" alt="">
                                    <div class="overlay">
                                        <div class="overlay-links">
                                             <a href="{{path('hub_show_professional', {'user': professional.getUser().getUser()})}}"><i class="fa fa-link"></i></a>
                                            <a href="{{asset("bundles/hub/perfil/" ~ professional.getUser().getPerfilphoto() )}}" class="popup-img"><i class="fa fa-search-plus"></i></a>
                                        </div>
                                        <span>View Detail</span>
                                    </div>
                                </div>
                                <div class="image-box-body">
                                    <h3 class="title"><a  href="{{path('hub_show_professional', {'user': professional.getUser().getUser()})}}">{{professional.getFirstname() ~ " " ~ professional.getLastname() }}</a></h3>
                                    <p>{{professional.getPresentation()}}</p>
                                    <a  href="{{path('hub_show_professional', {'user': professional.getUser().getUser()})}}"class="link"><span>Read More</span></a>
                                </div>
                            </div>
                        </div>
                       {% endfor %}
                    </div>
                <!-- main end -->

            </div>
        </div>
    </section>
    <!-- main-container end -->

    <!-- section start -->
    <!-- ================ -->
    <div class="section gray-bg text-muted footer-top clearfix">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="owl-carousel clients">
                        <div class="client">
                            <a href="#"><img src="{{asset('bundles/hub/images/client-1.png')}}" alt=""></a>
                        </div>
                        <div class="client">
                            <a href="#"><img src="{{asset('bundles/hub/images/client-2.png')}}" alt=""></a>
                        </div>
                        <div class="client">
                            <a href="#"><img src="{{asset('bundles/hub/images/client-3.png')}}" alt=""></a>
                        </div>
                        <div class="client">
                            <a href="#"><img src="{{asset('bundles/hub/images/client-4.png')}}" alt=""></a>
                        </div>
                        <div class="client">
                            <a href="#"><img src="{{asset('bundles/hub/images/client-5.png')}}" alt=""></a>
                        </div>
                        <div class="client">
                            <a href="#"><img src="{{asset('bundles/hub/images/client-6.png')}}" alt=""></a>
                        </div>
                        <div class="client">
                            <a href="#"><img src="{{asset('bundles/hub/images/client-7.png')}}" alt=""></a>
                        </div>
                        <div class="client">
                            <a href="#"><img src="{{asset('bundles/hub/images/client-8.png')}}" alt=""></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <blockquote class="inline">
                        <p class="margin-clear">Design is not just what it looks like and feels like. Design is how it works.</p>	
                        <footer><cite title="Source Title">Steve Jobs </cite></footer>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>
    <!-- section end -->
{% endblock %}

src/Hub/HubBundle/Resources/views/Default/list_products_and_services.html.twig
{# empty Twig template #}

{% extends 'head_Template.html.twig' %}

{% block color %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        {% if app.user.roles[0] == "ROLE_BUSINESS"  %}
           <link href="{{asset('bundles/hub/css/skins/pink.css')}}" rel="stylesheet">
        {% elseif app.user.roles[0] == "ROLE_PROFESSIONAL"  %}
            <link href="{{asset('bundles/hub/css/skins/orange.css')}}" rel="stylesheet">
        {% elseif app.user.roles[0] == "ROLE_USER" %}   
            <link href="{{asset('bundles/hub/css/skins/blue.css')}}" rel="stylesheet">
        {% else %}
            <link href="{{asset('bundles/hub/css/skins/red.css')}}" rel="stylesheet">
        {% endif %}    
    {% endif %}
{% endblock %}

{% block content %}

			<!-- banner start -->
			<!-- ================ -->
			<div class="banner shop-banner">

				<!-- slideshow start -->
				<!-- ================ -->
				<div class="slideshow white-bg">
					
					<!-- slider revolution start -->
					<!-- ================ -->
					<div class="slider-banner-container">
						<div class="slider-banner">
							<ul>
								<!-- slide 1 start -->
								<li data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-saveperformance="on" data-title="Slide 1">
								
								<!-- main image -->
								<img src="{{asset('bundles/hub/images/slider-shop-slide-1.jpg')}}"  alt="slidebg1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">

								<!-- Translucent background -->
								<div class="tp-caption light-translucent-bg"
									data-x="center"
									data-y="bottom"
									data-speed="800"
									data-start="0"
									style="background-color:rgba(255,255,255,0.4);">
								</div>

								<!-- LAYER NR. 1 -->
								<div class="tp-caption very_large_text hidden-sm black sfl tp-resizeme"
									data-x="center"
									data-y="150" 
									data-speed="200"
									data-start="0"
									data-end="10000"
									data-endspeed="200"
									data-splitin="chars"
									data-elementdelay="0.07"
									data-endelementdelay="0.1"
									data-splitout="chars">Up To 50% Sales
								</div>

								<!-- LAYER NR. 2 -->
								<div class="tp-caption tp-resizeme hidden-sm sfb"
									data-x="center"
									data-y="230" 
									data-speed="700"
									data-start="600"
									data-end="10000"
									data-endspeed="600"><a href="page-services.html" class="btn btn-dark">Offers <i class="fa fa-angle-right pl-10"></i></a>
								</div>

								</li>
								<!-- slide 1 end -->

								<!-- slide 2 start -->
								<li data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-saveperformance="on" data-title="Slide 2">
								
								<!-- main image -->
								<img src="{{asset('bundles/hub/images/slider-shop-slide-2.jpg')}}"  alt="slidebg1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">

								<!-- Translucent background -->
								<div class="tp-caption light-translucent-bg"
									data-x="center"
									data-y="bottom"
									data-speed="800"
									data-start="0"
									style="background-color:rgba(255,255,255,0.4);">
								</div>

								<!-- LAYER NR. 1 -->
								<div class="tp-caption very_large_text hidden-sm sft black tp-resizeme"
									data-x="center"
									data-y="150" 
									data-speed="700"
									data-start="200"
									data-end="10000"
									data-endspeed="600">Special Offers
								</div>

								<!-- LAYER NR. 2 -->
								<div class="tp-caption tp-resizeme hidden-sm sfb"
									data-x="center"
									data-y="230" 
									data-speed="700"
									data-start="600"
									data-end="10000"
									data-endspeed="600"><a href="page-services.html" class="btn btn-dark">Learn More <i class="fa fa-angle-right pl-10"></i></a>
								</div>

								</li>
								<!-- slide 2 end -->

							</ul>
						</div>
					</div>
					<!-- slider revolution end -->

				</div>
				<!-- slideshow end -->

				<div class="sorting-filters">
					<div class="container">
						<form class="form-inline">
							<div class="form-group">
								<label>Main Category</label>
								<select class="form-control">
									<option selected="selected">Automotive</option>
									<option>Business Support & Supplies</option>
									<option>Computer & Electronics</option>
                                 <option>Construction & Contractor</option>
                                 <option>Education</option>
                                 <option>Entertainment</option>
                                 <option>Food & Dinning</option>
                                  <option>Health & Medicine</option>
                                   <option>Home & Garden</option>
                                    <option>Legal & Financial</option>
                                     <option>Manufaturing,Whole Sale, Distribution</option>
                                      <option>Merchants(Retail)</option>
                                       <option>Miscellaneous</option>
                                        <option>Personal Care & Services</option>
                                         <option>Real Estates</option>
                                          <option>Travel & Transport</option>
                                         


								</select>
							</div>
							<div class="form-group">
								<label>Sub-Category</label>
								<select class="form-control">
									<option selected="selected">Auto Accesssories</option>
									<option>Auto Dealers- New</option>
                                    <option>Auto Dealers - Used</option>
                                    <option>Details & CarWash</option>
                                    <option>Gas Stations</option>
                                    <option>Motorcycle Sales & Repairs</option>
                                    <option>Rentals & Leasing</option>
                                    <option>Service, Repair & Parts</option>
                                    <option>Towing</option>
                                    <option>Body Works</option>
                                    <option>Painting</option>
								</select> 
							</div>
							<div class="form-group">
								<label>By Name</label>
								<div class="row grid-space-10">
									<div class="col-sm-6">
										<input type="text" class="form-control">
									</div>
									<div class="col-sm-6">
										<input type="text" class="form-control col-xs-6">
									</div>
								</div>
							</div>
							<div class="form-group">
								<label>Sort By</label>
								<select class="form-control">
									<option selected="selected">Name</option>
									<option>Type</option>
									<option>Location</option>
									<option>Rating High</option>
									<option>Ratting Low</option>
									<option>A-Z</option>
                                 <option>Z-A</option>
								</select> 
							</div>
							<div class="form-group">
								<a href="#" class="btn btn-default">Search</a>
							</div>
						</form>
					</div>
				</div>

			</div>
			<!-- banner end -->

			<!-- main-container start -->
			<!-- ================ -->
			<section class="main-container">

				<div class="container">
					<div class="row">

						<!-- main start -->
						<!-- ================ -->
						<div class="main col-md-12">

							<!-- page-title start -->
							<!-- ================ -->
							<h1 class="page-title">Products and Services</h1>
							<div class="separator-2"></div>
							<p class="lead">Products and services in yours hands <br class="hidden-sm hidden-xs"></p>
							<!-- page-title end -->
							
							<!-- shop items start -->
                                                       

							<div class="masonry-grid-fitrows row grid-space-20">
                                                            {% for p in pands %}
								<div class="col-md-3 col-sm-6 masonry-grid-item">
									<div class="listing-item">
										<div class="overlay-container">
											<img src="{{asset("bundles/hub/perfil/" ~ p.getPhoto() )}}" alt="">
											<a href="" class="overlay small">
												<i class="fa fa-plus"></i>
												<span>View Details</span>
											</a>
										</div>
										<div class="listing-item-body clearfix">
											<h3 class="title"><a href="">{{p.getName()}}</a></h3>
											<p>{{p.getDescription()}}</p>
											<span class="price">Status</span>
											<div class="elements-list pull-right">
												<i class="fa fa-signal"></i>
												<a href=""><i class="fa fa-eye pr-10"></i>Take a look</a>
											</div>
										</div>
									</div>
                                                                </div>
                                                                {% endfor %}
							<!-- shop items end -->
							
							<div class="clearfix"></div>

						</div>
						<!-- main end -->

					</div>
				</div>
			</section>
			<!-- main-container end -->

{% endblock%}

src/Hub/HubBundle/Resources/views/Default/test.html.twig
{# empty Twig template #}
{% extends 'head_Template.html.twig' %}

{% block content %}
hola mundo!!    
{% endblock %}

{% block notification %}
<div class="btn-group dropdown">    
    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i> Cart (8)</button>
    <ul class="dropdown-menu dropdown-menu-right dropdown-animation cart">
            <li>
                    <table class="table table-hover">
                            <thead>
                                    <tr>
                                            <th class="quantity">QTY</th>
                                            <th class="product">Product</th>
                                            <th class="amount">Subtotal</th>
                                    </tr>
                            </thead>
                            <tbody>
                                    <tr>
                                            <td class="quantity">2 x</td>
                                            <td class="product"><a href="shop-product.html">Android 4.4 Smartphone</a><span class="small">4.7" Dual Core 1GB</span></td>
                                            <td class="amount">$199.00</td>
                                    </tr>
                                    <tr>
                                            <td class="quantity">3 x</td>
                                            <td class="product"><a href="shop-product.html">Android 4.2 Tablet</a><span class="small">7.3" Quad Core 2GB</span></td>
                                            <td class="amount">$299.00</td>
                                    </tr>
                                    <tr>
                                            <td class="quantity">3 x</td>
                                            <td class="product"><a href="shop-product.html">Desktop PC</a><span class="small">Quad Core 3.2MHz, 8GB RAM, 1TB Hard Disk</span></td>
                                            <td class="amount">$1499.00</td>
                                    </tr>
                                    <tr>
                                            <td class="total-quantity" colspan="2">Total 8 Items</td>
                                            <td class="total-amount">$1997.00</td>
                                    </tr>
                            </tbody>
                    </table>
                    <div class="panel-body text-right">	
                    <a href="shop-cart.html" class="btn btn-group btn-default btn-sm">View Cart</a>
                    <a href="shop-checkout.html" class="btn btn-group btn-default btn-sm">Checkout</a>
                    </div>
            </li>
    </ul>
</div>
{% endblock %}
    
    
    
    